WTC/core/views.py
import math
from flask import render_template,Blueprint,redirect,url_for,session
from WTC.contact.forms import ContactUs
from WTC.core.forms import Bmr
from flask_login import login_required
core = Blueprint('core',__name__)


@core.route('/')
def index():
    form = ContactUs()
    return render_template('index.html',form=form)

@core.route('/bmr',methods=['GET','POST'])
@login_required
def bmr():
    form = Bmr()
    if form.validate_on_submit():
        session['age'] = form.age.data
        session['weight'] = form.weight.data
        session['height'] = form.height.data
        session['gender'] = form.gender.data 
        if session['gender'] == 'Male':
            bmr = 66.47 + (13.75 * session['weight'] ) + (5.003 * session['height']  ) - (6.755 * session['age'] )
            return render_template('bmr.html',bmr=(math.floor(bmr)),form=form)
        elif session['gender'] == 'Female':
            bmr =  655.1 + (9.563 * session['weight'] ) + (1.85 * session['height'] ) - (4.676 * session['age'])
            return render_template('bmr.html',bmr=(math.floor(bmr)),form=form)
    return render_template('bmr.html',form=form)

WTC/users/views.py
from flask import render_template,redirect,url_for,Blueprint,flash,abort,request
from WTC.users.forms import RegistrationForm,LoginForm,WorkoutPlan
from WTC import db
from flask_login import login_user,login_required,logout_user,current_user
from WTC.models import User,WorkoutPlanModel

users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,username=form.username.data,
                    billing_adress=form.billing_adress.data,pincode=form.pincode.data,
                    password=form.password.data )
        db.session.add(user)
        db.session.commit()
        flash('Thank you for Registring with us')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

@users.route('/login',methods=['GET','POST'])
def login():
   form = LoginForm()
   if form.validate_on_submit():
       user = User.query.filter_by(email=form.email.data).first()

       if user.check_password(form.password.data) and user is not None:
           login_user(user)
           flash('You are Logged in Successfully!')
            #If user is trying to acces some page where login in required
           next = request.args.get('next')
           if next == None or not next[0] == '/':
               next = url_for('core.index')
           return redirect(next)
   return render_template('login.html',form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You are logged out!')
    return redirect(url_for('core.index'))

@users.route('/<username>/make-workout-routine',methods=['GET','POST'])
@login_required
def workoutplan(username):
    
    

    form = WorkoutPlan()

    if form.validate_on_submit():
        add = WorkoutPlanModel(add=form.add.data,user_id=current_user.id)
        db.session.add(add)
        db.session.commit()
        flash('Workout Added')
        return redirect(url_for('users.workoutplan',username=username, **request.args))
    #grabbing all the added workouts to display them on template
    user = User.query.filter_by(username=username).first_or_404()
    addedexcerise_db = WorkoutPlanModel.query.filter_by(user_added_workout=user)

    return render_template('workout_plan.html',form=form,addedexcerise_db=addedexcerise_db,user=user)


@users.route('/<int:workoutplan_id>/delete',methods=['GET','POST'])
def delete(workoutplan_id):
    delete_excerise = WorkoutPlanModel.query.get_or_404(workoutplan_id)
    db.session.delete(delete_excerise)
    db.session.commit()
    username=current_user.username
    return redirect(url_for('users.workoutplan',username=username, **request.args))

@users.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

WTC/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <link rel="shortcut icon" href="/static/img/favicon.ico" />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="/static/img/apple-icon.png"
    />
    <link
      rel="stylesheet"
      href="/static/vendor/@fortawesome/fontawesome-free/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/creativetimofficial/tailwind-starter-kit/compiled-tailwind.min.css"
    />
    <link rel="stylesheet" href="/static/css/style.css">
    <title>WTC</title>
  </head>
  <body class="text-gray-800 antialiased">
    <nav
      class="top-0 absolute z-50 w-full flex flex-wrap items-center justify-between px-2 py-3 navbar-expand-lg"
    >
      <div
        class="container px-4 mx-auto flex flex-wrap items-center justify-between"
      >
        <div
          class="w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start"
        >
        
          <a
            class="text-sm font-bold leading-relaxed inline-block mr-4 py-2 whitespace-no-wrap uppercase text-white"
            href="{{url_for('core.index')}}"
            >HOME</a
          ><button
            class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
            type="button"
            onclick="toggleNavbar('example-collapse-navbar')"
          >
            <i class="text-white fas fa-bars"></i>
          </button>
        </div>
        <div
          class="lg:flex flex-grow items-center bg-white lg:bg-transparent lg:shadow-none hidden"
          id="example-collapse-navbar"
        >
          <ul class="flex flex-col lg:flex-row list-none mr-auto">
            <li class="flex items-center">
              <a
                class="lg:text-white lg:hover:text-gray-300 text-gray-800 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                href="#"
                ><i class="fas fa-blog"></i>BLOG </a>
            </li>
            {% if current_user.is_authenticated  %}
            <li class="flex items-center">
                <a
                  class="lg:text-white lg:hover:text-gray-300 text-gray-800 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                  href="{{url_for('users.profile')}}"
                  ><i class="far fa-user"></i>Profile </a
                >
              </li>
              <li class="flex items-center">
                <a class="lg:text-white lg:hover:text-gray-300 text-gray-800 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                 href="{{url_for('users.workoutplan',username=current_user.username)}}"> WORKOUT </a>
             </li>
             {% endif %}  
             <li class="flex items-center">
              <a class="lg:text-white lg:hover:text-gray-300 text-gray-800 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
               href="{{url_for('core.bmr')}}"><i class="fas fa-notes-medical"> </i> BMR </a>
           </li>
          </ul>
          <ul class="flex flex-col lg:flex-row list-none lg:ml-auto">
            <li class="flex items-center">
              <a
                class="lg:text-white lg:hover:text-gray-300 text-gray-800 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                href="https://github.com/HUSS41N/Workout-gym-web-application"
                ><i
                  class=" fab fa-github text-lg leading-lg "
                ></i
                ><span class="lg:hidden inline-block ml-2">Star</span></a
              >
            </li>
            {% if current_user.is_authenticated %}

            <li class="flex items-center">
              <a href="{{url_for('users.logout')}}">
              <button
                class="bg-white text-gray-800 active:bg-gray-100 text-xs font-bold uppercase px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none lg:mr-1 lg:mb-0 ml-3 mb-3"
                type="button"
                style="transition: all 0.15s ease 0s;">
                <i class="fas fa-sign-out-alt"></i> LOGOUT
              </button>
            </a> 
            </li>
            {% else %}
            <li class="flex items-center">
              <a href="{{url_for('users.register')}}">
              <button
                class="bg-white text-gray-800 active:bg-gray-100 text-xs font-bold uppercase px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none lg:mr-1 lg:mb-0 ml-3 mb-3"
                type="button"
                style="transition: all 0.15s ease 0s;">
               <i class="fas fa-user-plus"></i> SIGN UP
              </button>
            </a> 
            </li>
            <li class="flex items-center">
              <a href="{{url_for('users.login')}}">
                <button
                  class="bg-white text-gray-800 active:bg-gray-100 text-xs font-bold uppercase px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none lg:mr-1 lg:mb-0 ml-3 mb-3"
                  type="button"
                  style="transition: all 0.15s ease 0s;">
                   <i class="fas fa-sign-in-alt"></i> LOG IN
                </button>
              </a>
              </li>
              
              {% endif %}
          </ul>
        </div>
      </div>
      </nav>
    </div>
  </div>
</body>
<script>
    function toggleNavbar(collapseID) {
      document.getElementById(collapseID).classList.toggle("hidden");
      document.getElementById(collapseID).classList.toggle("block");
    }
  </script>
{% block content %}
    
{% endblock  %}
    
</html>

WTC/templates/bmr.html
{% extends 'base.html' %}

{% block content %}
<main>
    <section class="absolute w-full h-full">
      <div
        class="absolute top-0 w-full h-full bg-gray-900"
        style="background-image: url(./static/img/register_bg_2.png); background-size: 100%; background-repeat: no-repeat;"
      ></div>
     
      <div class="container mx-auto px-3 h-full">
        <div class="flex content-center items-center justify-center h-full">
          <div class="w-full lg:w-4/12 px-4">
            <div
              class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-gray-300 border-0"
            >
              <div class="rounded-t mb-0 px-3 py-4">
                <div class="text-center mb-3">
                  <h6 class="text-gray-600 text-sm font-bold">
                   
                  </h6>
                </div>
                <div class="btn-wrapper text-center">
                  <h1 id="result"><strong>{{bmr}} BMR</strong></h1>
                </div>
                <hr class="mt-3 border-b-1 border-gray-400" />
              </div>
              
              <div class="flex-auto px-4 lg:px-10 py-10 pt-0">
                <form action="" method="POST">
                  {{form.hidden_tag()}}
                  <div class="relative w-full mb-3">
                    
                    {{form.age.label(class="block uppercase text-gray-700 text-xs font-bold mb-2")}}
                    {{form.age(class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:shadow-outline w-full", placeholder="AGE",
                    id = 'age',
                    style="transition: all 0.15s ease 0s;")}}

                  </div>
                  
                  <div class="relative w-full mb-3">
                    
                    {{form.weight.label(class="block uppercase text-gray-700 text-xs font-bold mb-2")}}
                    {{form.weight(class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:shadow-outline w-full", placeholder="kg",
                    id = 'weight',
                    style="transition: all 0.15s ease 0s;")}}
                   
                  </div>
                 
                  <div class="relative w-full mb-3">
                    
                    {{form.height.label( class="block uppercase text-gray-700 text-xs font-bold mb-2")}}
                    {{form.height( class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:shadow-outline w-full",placeholder="cm",
                    id = 'height',
                    style="transition: all 0.15s ease 0s;")}}
                    
                  </div>

                    <div class="relative w-full">
                      
                      {{form.gender.label(class=" uppercase text-gray-700 text-xs font-bold mb-1")}}
                      {{form.gender(class="px-3 py-3 placeholder-gray-400 text-gray-700  text-sm ")}}
                      
                     </div>
                  
                  <div class="text-center mt-2">
                    {{form.submit(  class="bg-gray-900 text-white active:bg-gray-700 text-sm font-bold uppercase px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 w-full", style="transition: all 0.15s ease 0s;")}}
                    
                  </div>
                </form>
              </div>
            </div>
           </div>
          </div>
        </div>
      </div>
      <footer class="relative bg-gray-300 pt-8 pb-6">
        <div
          class="bottom-auto top-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden -mt-20"
          style="height: 80px; transform: translateZ(0px);"
        >
          <svg
            class="absolute bottom-0 overflow-hidden"
            xmlns="http://www.w3.org/2000/svg"
            preserveAspectRatio="none"
            version="1.1"
            viewBox="0 0 2560 100"
            x="0"
            y="0"
          >
            <polygon
              class="text-gray-300 fill-current"
              points="2560 0 2560 100 0 100"
            ></polygon>
          </svg>
        </div>
        <div class="container mx-auto px-4">
          <div class="flex flex-wrap">
            <div class="w-full lg:w-6/12 px-4">
              <h4 class="text-3xl font-semibold">Let's keep in touch!</h4>
              <h5 class="text-lg mt-0 mb-2 text-gray-700">
                Find us on any of these platforms, we respond 1-2 business days.
              </h5>
              <div class="mt-6">
                <button
                  class="bg-white text-blue-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                  type="button"
                >
                  <i class="flex fab fa-twitter"></i></button
                ><button
                  class="bg-white text-blue-600 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                  type="button"
                >
                  <i class="flex fab fa-facebook-square"></i></button
                ><button
                  class="bg-white text-pink-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                  type="button"
                >
                  <i class="flex fab fa-dribbble"></i></button
                ><button
                  class="bg-white text-gray-900 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2 p-3"
                  type="button"
                >
                  <i class="flex fab fa-github"></i>
                </button>
              </div>
            </div>
            <div class="w-full lg:w-6/12 px-4">
              <div class="flex flex-wrap items-top mb-6">
                <div class="w-full lg:w-4/12 px-4 ml-auto">
                  <span
                    class="block uppercase text-gray-600 text-sm font-semibold mb-2"
                    >Useful Links</span
                  >
                  <ul class="list-unstyled">
                    <li>
                      <a
                        class="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                        href="#"
                        >About Us</a
                      >
                    </li>
                    <li>
                      <a
                        class="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                        href="#"
                        >Blog</a
                      >
                    </li>
                    <li>
                      <a
                        class="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                        href="#"
                        >Github</a
                      >
                    </li>
                  </ul>
                </div>
                <div class="w-full lg:w-4/12 px-4">
                  <span
                    class="block uppercase text-gray-600 text-sm font-semibold mb-2"
                    >Other Resources</span
                  >
                  <ul class="list-unstyled">
                   
                    <li>
                      <a
                        class="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                        href="#"
                        >Terms &amp; Conditions</a
                      >
                    </li>
                    <li>
                      <a
                        class="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                        href="#"
                        >Privacy Policy</a
                      >
                    </li>
                    <li>
                      <a
                        class="text-gray-700 hover:text-gray-900 font-semibold block pb-2 text-sm"
                        href="#"
                        >Contact Us</a
                      >
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-6 border-gray-400" />
          <div
            class="flex flex-wrap items-center md:justify-between justify-center"
          >
            <div class="w-full md:w-4/12 px-4 mx-auto text-center">
              <div class="text-sm text-gray-600 font-semibold py-1">
                Copyright © 2020 WTC ©
              </div>
            </div>
          </div>
        </div>
      </footer>
      
     
     
    </section>
  </main>
 
{% endblock  %}



    
    

WTC/templates/login.html
{% extends 'base.html' %}


{% block content %}
<main>
    <section class="absolute w-full h-full">
      <div
        class="absolute top-0 w-full h-full bg-gray-900"
        style="background-image: url(./static/img/register_bg_2.png); background-size: 100%; background-repeat: no-repeat;"
      ></div>
     
      <div class="container mx-auto px-3 h-full">
        <div class="flex content-center items-center justify-center h-full">
          <div class="w-full lg:w-4/12 px-4">
            <div
              class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-gray-300 border-0"
            >
              <div class="rounded-t mb-0 px-3 py-4">
                <div class="text-center mb-3">
                  <h6 class="text-gray-600 text-sm font-bold">
                   
                  </h6>
                </div>
                <div class="btn-wrapper text-center">
                  <h1 id="result"><strong>SIGN IN</strong></h1>
                </div>
                <hr class="mt-3 border-b-1 border-gray-400" />
              </div>
              
              <div class="flex-auto px-4 lg:px-10 py-10 pt-0">
                <form action="" method="POST">
                  {{form.hidden_tag()}}
                  <div class="relative w-full mb-3">
                    
                    {{form.email.label(class="block uppercase text-gray-700 text-xs font-bold mb-2")}}
                    {{form.email(class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:shadow-outline w-full", placeholder="Email",
                                   style="transition: all 0.15s ease 0s;")}}

                  </div>
                  
                  <div class="relative w-full mb-3">
                    
                    {{form.password.label(class="block uppercase text-gray-700 text-xs font-bold mb-2")}}
                    {{form.password(class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:shadow-outline w-full", placeholder="password",
                    style="transition: all 0.15s ease 0s;")}}
                   
                  </div>
                  
                  <div class="text-center mt-2">
                    {{form.submit(  class="bg-gray-900 text-white active:bg-gray-700 text-sm font-bold uppercase px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 w-full", style="transition: all 0.15s ease 0s;")}}
                    
                  </div>
                </form>
              </div>
            </div>
           </div>
          </div>
        </div>
      </div>
    </section>
    </main>
{% endblock  %}
    

WTC/templates/profile.html
{% extends 'base.html' %}


{% block content %}
<main class="profile-page">
    <section class="relative block" style="height: 500px;">
      <div
        class="absolute top-0 w-full h-full bg-center bg-cover"
        style='background-image: url("https://images.unsplash.com/photo-1499336315816-097655dcfbda?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=2710&amp;q=80");'
      >
        <span
          id="blackOverlay"
          class="w-full h-full absolute opacity-50 bg-black"
        ></span>
      </div>
      <div
        class="top-auto bottom-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden"
        style="height: 70px; transform: translateZ(0px);"
      >
        <svg
          class="absolute bottom-0 overflow-hidden"
          xmlns="http://www.w3.org/2000/svg"
          preserveAspectRatio="none"
          version="1.1"
          viewBox="0 0 2560 100"
          x="0"
          y="0"
        >
          <polygon
            class="text-gray-300 fill-current"
            points="2560 0 2560 100 0 100"
          ></polygon>
        </svg>
      </div>
    </section>
    <section class="relative py-16 bg-gray-300">
      <div class="container mx-auto px-4">
        <div
          class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64"
        >
          <div class="px-6">
            <div class="flex flex-wrap justify-center">
              <div
                class="w-full lg:w-3/12 px-4 lg:order-2 flex justify-center"
              >
                <div class="relative">
                  <img
                    alt="..."
                    src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80"
                    class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16"
                    style="max-width: 150px;"
                  />
                </div>
              </div>
              <div
                class="w-full lg:w-4/12 px-4 lg:order-3 lg:text-right lg:self-center"
              >
                <div class="py-6 px-3 mt-32 sm:mt-0">
                  <button
                    class="bg-pink-500 active:bg-pink-600 uppercase text-white font-bold hover:shadow-md shadow text-xs px-4 py-2 rounded outline-none focus:outline-none sm:mr-2 mb-1"
                    type="button"
                    style="transition: all 0.15s ease 0s;"
                  >
                    Connect
                  </button>
                </div>
              </div>
              <div class="w-full lg:w-4/12 px-4 lg:order-1">
                <div class="flex justify-center py-4 lg:pt-4 pt-8">
                  <div class="lg:mr-4 p-3 text-center">
                    <span
                      class="text-xl font-bold block uppercase tracking-wide text-gray-700"
                      >89</span
                    ><span class="text-sm text-gray-500">Comments</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center mt-12">
              <h3
                class="text-4xl font-semibold leading-normal mb-2 text-gray-800 mb-2"
              >
                Jenna Stones
              </h3>
              <div
                class="text-sm leading-normal mt-0 mb-2 text-gray-500 font-bold uppercase"
              >
                <i
                  class="fas fa-map-marker-alt mr-2 text-lg text-gray-500"
                ></i>
                Los Angeles, California
              </div>
              <div class="mb-2 text-gray-700 mt-10">
                <i class="fas fa-briefcase mr-2 text-lg text-gray-500"></i
                >Solution Manager - Creative Tim Officer
              </div>
              <div class="mb-2 text-gray-700">
                <i class="fas fa-university mr-2 text-lg text-gray-500"></i
                >University of Computer Science
              </div>
            </div>
            <div class="mt-10 py-10 border-t border-gray-300 text-center">
              <div class="flex flex-wrap justify-center">
                <div class="w-full lg:w-9/12 px-4">
                  <p class="mb-4 text-lg leading-relaxed text-gray-800">
                    An artist of considerable range, Jenna the name taken by
                    Melbourne-raised, Brooklyn-based Nick Murphy writes,
                    performs and records all of his own music, giving it a
                    warm, intimate feel with a solid groove structure. An
                    artist of considerable range.
                  </p>
                  <a href="#pablo" class="font-normal text-pink-500"
                    >Show more</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
{% endblock  %}
    

WTC/templates/workout_plan.html
{% extends 'base.html' %}


{% block content %}

    <main>
        <section class="absolute w-full h-full">
          <div
            class="absolute top-0 w-full h-full bg-gray-900"
            style="background-image: url(./static/img/register_bg_2.png); background-size: 100%; background-repeat: no-repeat;"
          ></div>
         
          <div class="container mx-auto px-3 h-full">
            <div class="flex content-center items-center justify-center h-full">
              <div class="w-full lg:w-4/12 px-4">
                <div
                  class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-gray-300 border-0"
                >
                  <div class="rounded-t mb-0 px-3 py-4">
                    <div class="text-center mb-3">
                      <h6 class="text-gray-600 text-sm font-bold">
                       
                      </h6>
                    </div>
                    <div class="btn-wrapper text-center" id="container">
                      <h1 id="result"><strong>MAKE YOUR WORKOUT PLAN</strong></h1>
                    </div>
                    <hr class="mt-3 border-b-1 border-gray-400" />
                  </div>
                  
                  <div class="flex-auto px-4 lg:px-10 py-10 pt-0">
                    <form action="" method="POST">
                      {{form.hidden_tag()}}
                      <div class="relative w-full mb-3">
                        
                        {{form.add.label(class="block uppercase text-gray-700 text-xs font-bold mb-2")}}
                        {{form.add(class="px-3 py-3 placeholder-gray-400 text-gray-700 bg-white rounded text-sm shadow focus:outline-none focus:shadow-outline w-full", placeholder="ADD EXCERCISE HERE",
                                       style="transition: all 0.15s ease 0s;")}}
    
                      </div>

                      <div class="text-center mt-2">
                        {{form.submit(  class="bg-gray-900 text-white active:bg-gray-700 text-sm font-bold uppercase px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 w-full", style="transition: all 0.15s ease 0s;")}}
                        
                      </div>

                    </form>
                    <div class="mt-2">
                        <ul>
                            {% for user_excerise in addedexcerise_db %}
                                    <li class="block uppercase text-gray-700 text-xs font-bold mb-2 pl-7">{{user_excerise}} <span class="ml-10"> <a href="{{url_for('users.delete',workoutplan_id=user_excerise.id)}}" class="bg-gray-900 text-white active:bg-gray-700 text-sm font-bold uppercase px-3 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-6 ml-6 w-full"><i class="fas fa-trash "></i></a>  </span> </li>
                            {% endfor %}
                            </ul> 
                           
                      </div>
                  </div>
                </div>
               </div>
              </div>
            </div>
          </div>
        </section>
        </main>
{% endblock  %}
    